### PR TITLE
Make displayId an attribute instead of query param

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1: Just so I understand, what's the reasoning for the change?

**Comment by donnapep** [comment]
@stulees It didn't really make any sense to have it be part of the URL in the first place, so I changed it to keep it more aligned with how other components work.

**Comment by stulees** [comment]
@donnapep Okay thanks

**Pull request merged**
