### PR TITLE
Remove src attribute from iron-component-page

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees The Github pages structure is better, but there's still no `index.html` page in `components/rise-page`. Do you see anything else I may have missed? Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1: Looked at your repo and I think you need to name `demo.html` to `index.html`.

**Comment by donnapep** [comment]
@stulees OK, thanks. I renamed that file and made some additional changes. Hopefully it will work this time. Please review again. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Pull request merged**
