### PR TITLE
Update bower dependencies

### PR DESCRIPTION
**Pull request by donnapep**
- Bumping the version and tagging a new release should hopefully fix the problem of Github pages not working.
- Updated the bower dependencies to account for new repo names.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by donnapep** [comment]
@alex-deaconu Since Stu is away today, would you mind reviewing this one? Thx.

**Comment by alex-deaconu** [comment]
@donnapep looks good :+1: . Thanks.

**Comment by donnapep** [comment]
Thanks @alex-deaconu.

**Pull request merged**
